package com.syz.community.model;

public class Thumb {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column THUMB.ID
     *
     * @mbg.generated Sun Apr 18 20:49:22 JST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column THUMB.THUMB_ID
     *
     * @mbg.generated Sun Apr 18 20:49:22 JST 2021
     */
    private Integer thumbId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column THUMB.THUMB_ID_PARENT
     *
     * @mbg.generated Sun Apr 18 20:49:22 JST 2021
     */
    private Integer thumbIdParent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column THUMB.ID
     *
     * @return the value of THUMB.ID
     *
     * @mbg.generated Sun Apr 18 20:49:22 JST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column THUMB.ID
     *
     * @param id the value for THUMB.ID
     *
     * @mbg.generated Sun Apr 18 20:49:22 JST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column THUMB.THUMB_ID
     *
     * @return the value of THUMB.THUMB_ID
     *
     * @mbg.generated Sun Apr 18 20:49:22 JST 2021
     */
    public Integer getThumbId() {
        return thumbId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column THUMB.THUMB_ID
     *
     * @param thumbId the value for THUMB.THUMB_ID
     *
     * @mbg.generated Sun Apr 18 20:49:22 JST 2021
     */
    public void setThumbId(Integer thumbId) {
        this.thumbId = thumbId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column THUMB.THUMB_ID_PARENT
     *
     * @return the value of THUMB.THUMB_ID_PARENT
     *
     * @mbg.generated Sun Apr 18 20:49:22 JST 2021
     */
    public Integer getThumbIdParent() {
        return thumbIdParent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column THUMB.THUMB_ID_PARENT
     *
     * @param thumbIdParent the value for THUMB.THUMB_ID_PARENT
     *
     * @mbg.generated Sun Apr 18 20:49:22 JST 2021
     */
    public void setThumbIdParent(Integer thumbIdParent) {
        this.thumbIdParent = thumbIdParent;
    }
}