package com.syz.community.mapper;

import com.syz.community.model.Thumb;
import com.syz.community.model.ThumbExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ThumbMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table THUMB
     *
     * @mbg.generated Sun Apr 18 20:49:22 JST 2021
     */
    long countByExample(ThumbExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table THUMB
     *
     * @mbg.generated Sun Apr 18 20:49:22 JST 2021
     */
    int deleteByExample(ThumbExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table THUMB
     *
     * @mbg.generated Sun Apr 18 20:49:22 JST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table THUMB
     *
     * @mbg.generated Sun Apr 18 20:49:22 JST 2021
     */
    int insert(Thumb record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table THUMB
     *
     * @mbg.generated Sun Apr 18 20:49:22 JST 2021
     */
    int insertSelective(Thumb record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table THUMB
     *
     * @mbg.generated Sun Apr 18 20:49:22 JST 2021
     */
    List<Thumb> selectByExample(ThumbExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table THUMB
     *
     * @mbg.generated Sun Apr 18 20:49:22 JST 2021
     */
    Thumb selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table THUMB
     *
     * @mbg.generated Sun Apr 18 20:49:22 JST 2021
     */
    int updateByExampleSelective(@Param("record") Thumb record, @Param("example") ThumbExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table THUMB
     *
     * @mbg.generated Sun Apr 18 20:49:22 JST 2021
     */
    int updateByExample(@Param("record") Thumb record, @Param("example") ThumbExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table THUMB
     *
     * @mbg.generated Sun Apr 18 20:49:22 JST 2021
     */
    int updateByPrimaryKeySelective(Thumb record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table THUMB
     *
     * @mbg.generated Sun Apr 18 20:49:22 JST 2021
     */
    int updateByPrimaryKey(Thumb record);
}